name: Unit Testing Execution

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
jobs:
  unit-teting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run unit tests with Maven
      run: mvn test

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      id: jacoco
      with:
        generate-branches-badge: true
        jacoco-csv-file: target/site/jacoco/jacoco.csv
        fail-if-coverage-less-than: 50
        fail-if-branches-less-than: 50

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"