name: Unit Testing Execution

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      distribution:
        required: true
        type: string
      coverage:
        required: true
        type: string

jobs:
  unit-teting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code repository
      uses: actions/checkout@v4
      with:
        path: './repo-code'
    
    - name: Checkout templates repository
      uses: actions/checkout@v4
      with:
        repository: 'kevardila/personal_workflows'
        ref: 'v5.0.0'
        path: './repo-templates'
        sparse-checkout: |
          Dockerfile
        sparse-checkout-cone-mode: false
    
    - name: show repo code
      run: |
        cd repo-code
        ls

    - name: show repo templates
      run: |
        cd repo-templates
        ls

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}

    - name: Run unit tests with Maven
      run: |
        cd './repo-code'
        mvn test

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      id: jacoco
      with:
        generate-branches-badge: true
        jacoco-csv-file: target/site/jacoco/jacoco.csv
        fail-if-coverage-less-than: ${{ inputs.coverage }}
        fail-if-branches-less-than: ${{ inputs.coverage }}

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"